dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
  - osx
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - BROWSER='safari 10.1'
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm run test:once
  - npm run e2e
